### PR TITLE
my project CamplyIN - A camp ground project

### PR DESCRIPTION
**Pull request by Bikaskumar572**
heroku link : https://bikas-camply.herokuapp.com/
github link : https://github.com/Bikaskumar572

### CODE REVIEW

**Comment by Bikaskumar572** [comment]
@Yashika1410 , please check out my project

**Comment by Yashika1410** [comment]
Ok i will suggest different pr for the another that will increase pr count in your hacktoberfest profile and if you no issues i will just merge this request.
Thanks for contributing.

**Comment by Bikaskumar572** [comment]
@Yashika1410 , ya sure please create a different pr and then merge.

**Comment by Yashika1410** [comment]
@Bikaskumar572 you have to create a different pr i can't do it

**Pull request merged**
