### PR TITLE
Create start.html

### PR DESCRIPTION
**Pull request by confusedgenius**
Added JS ANALOG CLOCK

### CODE REVIEW

**Comment by Yashika1410** [comment]
Hi @confusedgenius please add your details in contributors.md and update this pr and also can you share a screen shot of this project.

**Comment by confusedgenius** [comment]
> Hi @confusedgenius please add your details in contributors.md and update this pr and also can you share a screen shot of this project.

I have added my name in [contributors.md](https://github.com/Yashika1410/HacktoberFest-2022/blob/main/contributors.md).Thankyou!!

**Comment by confusedgenius** [comment]
> > Hi @confusedgenius please add your details in contributors.md and update this pr and also can you share a screen shot of this project.
> 
> I have added my name in [contributors.md](https://github.com/Yashika1410/HacktoberFest-2022/blob/main/contributors.md).Thankyou!!



> > Hi @confusedgenius please add your details in contributors.md and update this pr and also can you share a screen shot of this project.
> 
> I have added my name in [contributors.md](https://github.com/Yashika1410/HacktoberFest-2022/blob/main/contributors.md).Thankyou!!

**Comment by confusedgenius** [comment]
> > Hi @confusedgenius please add your details in contributors.md and update this pr and also can you share a screen shot of this project.
> 


JS ANALOG CLOCK SCREENSHOT
Capture

**Pull request merged**
