### PR TITLE
todo_react

### PR DESCRIPTION
**Pull request by Shiyadh123**
Solved issue #4

### CODE REVIEW

**Comment by Yashika1410** [comment]
Please add your details in contributors.md

**Review by Yashika1410 — APPROVED** [review]

**Comment by Shiyadh123** [comment]
Done @Yashika1410

**Comment by Shiyadh123** [comment]
Please merge this PR @Yashika1410

**Comment by Yashika1410** [comment]
Hi @Shiyadh123 please make a separate pull request for Contact-Manager and also you still didn't add your details in contributors.md

**Comment by Yashika1410** [comment]
No worries i just saw another request i will merge both

**Pull request merged**
